# Exemplos de código com Numpy

Numpy é uma biblioteca para agilizar operações matemáticas em python.

Para utilizar o numpy é necessário importá-lo:

In [8]:
import numpy as np

Uma grande vantegem do numpy é a utilização de array de dados homogêneos. 

Por padrão python utiliza o conceito de lista, que pode ser lento para operaçẽs matemáticas.

Os arrays do numpy carregam dados de tamanho fixo, agilizanddo as operações, além de metadados que são informações sobre os dados do array, como por exempo tamanho, tipo utilizado para o dado, taamanho em bytes, etc.

In [18]:
#exemplo de array com numpy
data = np.arange(5)

print(data)

#dimensões do array
print(data.shape)

#tipo de dado utilizado no array
print(data.dtype)


#cria um array utizando uma lista do python
data = np.array([[1,2,3], [4,5,6]])

print("Exemplo de array criado com dados python")

print(data)

print(data.dtype)


#cria um array de tipo diferente
data = np.array([[1,2,3], [4,5,6]], dtype="float64")

print(data)
print(data.dtype)


[0 1 2 3 4]
(5,)
int64
Exemplo de array criado com dados python
[[1 2 3]
 [4 5 6]]
int64
[[1. 2. 3.]
 [4. 5. 6.]]
float64


Os acessos aos dados dos arrays e matrizes do numpy são similares ao da lista python

In [28]:
#acessando primeiro elemento
print(data[0]) 

#acessando matriz
print(data[0][0])

#acessanddo todos os elementos a partir da primeira linha até a primeira coluna
print(data[1:, :1])

[1. 2. 3.]
1.0
[[4.]]


## Tipos de dados 
Existem diversos tipos de dados com diferentes tamanhos em numpy


|tipo|tamanho|
|----|-------|
|bool | Verdadeiro ou Falso (1 bit)|
|int8| Inteiro de um Byte (-128, 127)|
|int16 | Inteiro 2 Bytes (-32768, 32767)|
|int32 | Inteiro 4 Bytes ($-2^{31}$, $2^{31} - 1$)|
|int64 | Inteiro 8 Bytes ($-2^{63}$, $2^{63} - 1$)|
|uint8 | Inteiro sem sinal (0, 255)|
|uint16 | Inteiro sem sinal (0, 65535)|
|float16| Ponto flutuante de 16 bits|
|float32 | Ponto flutuante de 32 bits|
|float64 | Ponto flutuante de 64 bits|
|complex64 | Número complexo que utiliza 2 float32|
|complex128| Número complexo que utiliza 2 float64|

In [34]:
print("Inteiro")
inteiro_8bits = np.int8(7)
print(inteiro_8bits)
print(inteiro_8bits.dtype)

print("\nPonto flutuante")
ponto_flutuante = np.float16(222)
print(ponto_flutuante)
print(ponto_flutuante.dtype)

print("\nArray com tipo definido")
array_float = np.arange(5, dtype=np.float16)
print(array_float)
print(array_float.dtype)


Inteiro
7
int8

Ponto flutuante
222.0
float16

Array com tipo definido
[0. 1. 2. 3. 4.]
float16


## Manipulando a forma do array

Com numpy pode-se manipular a forma do array e matriz com métodos simples

In [37]:
data = np.arange(25)

print(data)

#transforma em uma matriz 5x5
data = data.reshape(5,5)

print(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [41]:
#passa para o formato unidimensional
print(data.ravel())

print(data.flatten())


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [43]:
#manipula diretamente o formato do array

data.shape = (25, 1)

print(data)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]]


## Stacking - Concatenando arrays

Pode-se concatenar matrizes horizontal e verticalmente com numpy

In [49]:
data = np.arange(25).reshape(5,5)

new_data = data * 2

print(data)
print('\n\n')
print(new_data)


print('\n\n')
print('Concatenando horizontalmente')
# O argumento é uma tupla com os dados a serem concatenados
print(np.hstack((data, new_data)))

print('\n\n')
print('Concatenando verticalmente')
print(np.vstack((data, new_data)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]



[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]



Concatenando horizontalmente
[[ 0  1  2  3  4  0  2  4  6  8]
 [ 5  6  7  8  9 10 12 14 16 18]
 [10 11 12 13 14 20 22 24 26 28]
 [15 16 17 18 19 30 32 34 36 38]
 [20 21 22 23 24 40 42 44 46 48]]



Concatenando verticalmente
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]
